# Generated by Django 4.1 on 2022-08-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_photo_animal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='care_log',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['-date']},
        ),
    ]
