# Generated by Django 4.1 on 2022-08-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_care_log_options_alter_feeding_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care_log',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description of Care'),
        ),
    ]
